"""create initial schema

Revision ID: 0bbf40f2c677
Revises: 
Create Date: 2026-05-10 20:39:05.555133
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '0bbf40f2c677'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('counterparties',
    sa.Column('user_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('person', 'bank', 'business', 'family', 'friend', 'other', name='counterparty_type_enum'), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_counterparties_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_counterparties'))
    )
    op.create_index(op.f('ix_counterparties_user_id'), 'counterparties', ['user_id'], unique=False)
    op.create_index('ix_counterparties_user_name', 'counterparties', ['user_id', 'name'], unique=False)
    op.create_table('expense_categories',
    sa.Column('user_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('color', sa.String(length=32), nullable=True),
    sa.Column('icon', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_expense_categories_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_expense_categories')),
    sa.UniqueConstraint('user_id', 'slug', name=op.f('uq_expense_categories_user_id'))
    )
    op.create_index(op.f('ix_expense_categories_user_id'), 'expense_categories', ['user_id'], unique=False)
    op.create_table('monthly_income_configs',
    sa.Column('user_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('month', sa.SmallInteger(), nullable=False),
    sa.Column('base_income', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('extra_income', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('base_income >= 0', name=op.f('ck_monthly_income_configs_base_income_non_negative')),
    sa.CheckConstraint('extra_income >= 0', name=op.f('ck_monthly_income_configs_extra_income_non_negative')),
    sa.CheckConstraint('month BETWEEN 1 AND 12', name=op.f('ck_monthly_income_configs_valid_month')),
    sa.CheckConstraint('year BETWEEN 2000 AND 2100', name=op.f('ck_monthly_income_configs_valid_year')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_monthly_income_configs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_monthly_income_configs')),
    sa.UniqueConstraint('user_id', 'year', 'month', name=op.f('uq_monthly_income_configs_user_id'))
    )
    op.create_index(op.f('ix_monthly_income_configs_user_id'), 'monthly_income_configs', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens'))
    )
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('debts',
    sa.Column('user_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('counterparty_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('type', sa.Enum('receivable', 'payable', name='debt_type_enum'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'partially_paid', 'paid', 'cancelled', name='debt_status_enum'), nullable=False),
    sa.Column('origin_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('original_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('original_amount > 0', name=op.f('ck_debts_original_amount_positive')),
    sa.ForeignKeyConstraint(['counterparty_id'], ['counterparties.id'], name=op.f('fk_debts_counterparty_id_counterparties'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_debts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_debts'))
    )
    op.create_index(op.f('ix_debts_counterparty_id'), 'debts', ['counterparty_id'], unique=False)
    op.create_index(op.f('ix_debts_user_id'), 'debts', ['user_id'], unique=False)
    op.create_index('ix_debts_user_origin_date', 'debts', ['user_id', 'origin_date'], unique=False)
    op.create_index('ix_debts_user_type_status', 'debts', ['user_id', 'type', 'status'], unique=False)
    op.create_table('expenses',
    sa.Column('user_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('category_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('month', sa.SmallInteger(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('payment_method', sa.Enum('cash', 'debit_card', 'credit_card', 'transfer', 'digital_wallet', 'other', name='payment_method_enum'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name=op.f('ck_expenses_amount_positive')),
    sa.CheckConstraint('month BETWEEN 1 AND 12', name=op.f('ck_expenses_valid_month')),
    sa.CheckConstraint('year BETWEEN 2000 AND 2100', name=op.f('ck_expenses_valid_year')),
    sa.ForeignKeyConstraint(['category_id'], ['expense_categories.id'], name=op.f('fk_expenses_category_id_expense_categories'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_expenses_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_expenses'))
    )
    op.create_index('ix_expenses_user_category_id', 'expenses', ['user_id', 'category_id'], unique=False)
    op.create_index('ix_expenses_user_expense_date', 'expenses', ['user_id', 'expense_date'], unique=False)
    op.create_index('ix_expenses_user_year_month', 'expenses', ['user_id', 'year', 'month'], unique=False)
    op.create_table('debt_payments',
    sa.Column('user_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('debt_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name=op.f('ck_debt_payments_amount_positive')),
    sa.ForeignKeyConstraint(['debt_id'], ['debts.id'], name=op.f('fk_debt_payments_debt_id_debts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_debt_payments_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_debt_payments'))
    )
    op.create_index(op.f('ix_debt_payments_debt_id'), 'debt_payments', ['debt_id'], unique=False)
    op.create_index('ix_debt_payments_debt_payment_date', 'debt_payments', ['debt_id', 'payment_date'], unique=False)
    op.create_index(op.f('ix_debt_payments_user_id'), 'debt_payments', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_debt_payments_user_id'), table_name='debt_payments')
    op.drop_index('ix_debt_payments_debt_payment_date', table_name='debt_payments')
    op.drop_index(op.f('ix_debt_payments_debt_id'), table_name='debt_payments')
    op.drop_table('debt_payments')
    op.drop_index('ix_expenses_user_year_month', table_name='expenses')
    op.drop_index('ix_expenses_user_expense_date', table_name='expenses')
    op.drop_index('ix_expenses_user_category_id', table_name='expenses')
    op.drop_table('expenses')
    op.drop_index('ix_debts_user_type_status', table_name='debts')
    op.drop_index('ix_debts_user_origin_date', table_name='debts')
    op.drop_index(op.f('ix_debts_user_id'), table_name='debts')
    op.drop_index(op.f('ix_debts_counterparty_id'), table_name='debts')
    op.drop_table('debts')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_monthly_income_configs_user_id'), table_name='monthly_income_configs')
    op.drop_table('monthly_income_configs')
    op.drop_index(op.f('ix_expense_categories_user_id'), table_name='expense_categories')
    op.drop_table('expense_categories')
    op.drop_index('ix_counterparties_user_name', table_name='counterparties')
    op.drop_index(op.f('ix_counterparties_user_id'), table_name='counterparties')
    op.drop_table('counterparties')
    op.drop_table('users')
    # ### end Alembic commands ###
